import { HMZC_LOGO_DATA_URI } from "../../inspections/assets/logo";
import CertificateQR from "../../inspections/components/CertificateQR";
import { LineItem } from "../types/finance.types";
import "../../inspections/inspections.css"; // reuses .insp-letterhead/.insp-print-chk/.insp-badge etc. rather than duplicating them in finance.css

interface Props {
  kind: "INVOICE" | "QUOTATION";
  docNo: string;
  customer: string;
  vesselName: string | null;
  imoNo: string | null;
  status: string;
  lineItems: LineItem[];
  subtotal: number;
  discountTotal: number;
  total: number;
  issuedBy: string | null;
  issuedAt: string | null;
}

const watermarkStyle = { ["--insp-watermark-url" as any]: `url(${HMZC_LOGO_DATA_URI})` };

/**
 * "make the invoice have same characteristics as the certificate" — same
 * letterhead (logo + Cabinda/Luanda addresses), the same per-document QR
 * code, and the same faint watermark used on every certificate page
 * (CertificatePreview.tsx), applied here to invoices and quotations.
 */
export default function FinanceDocumentPreview({
  kind, docNo, customer, vesselName, imoNo, status, lineItems, subtotal, discountTotal, total, issuedBy, issuedAt,
}: Props) {
  return (
    <div className="finance-doc-page" style={watermarkStyle}>
      <div className="insp-letterhead">
        <img src={HMZC_LOGO_DATA_URI} alt="HMZC LTD" />
        <div className="insp-lh-right" style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
          <div>
            HMZC LTD — Marine Engineering Services<br />
            Cabinda HQ: Urbanização 4 De Abril, Cabinda, Angola<br />
            Luanda: N.º 5 Rua da Igreja (Vulgo Bento Raimundo), Próximo ao Mercado Kiffca,<br />
            Bairro Chinguar, Bairro Benfica-Talatona, Luanda<br />
            admin@hmzchealthinmarine.com&nbsp;|&nbsp;+244 972 320 300
          </div>
          <CertificateQR payload={`HMZC ${kind}\nNo: ${docNo}\nCustomer: ${customer || "—"}\nTotal: $${total.toFixed(2)}`} size={54} />
        </div>
      </div>

      <div className="insp-cert-title-row">
        <h2>{kind === "INVOICE" ? "Invoice" : "Quotation"}</h2>
        <span className="insp-badge" style={{ background: kind === "INVOICE" ? "var(--insp-navy)" : "var(--insp-teal)" }}>{status.toUpperCase()}</span>
      </div>

      <table className="insp-id-table">
        <tbody>
          <tr>
            <td className="insp-label-cell">{kind === "INVOICE" ? "Invoice No." : "Quotation No."}</td><td>{docNo}</td>
            <td className="insp-label-cell">Customer</td><td>{customer || "—"}</td>
          </tr>
          <tr>
            <td className="insp-label-cell">Vessel</td><td>{vesselName || "—"}</td>
            <td className="insp-label-cell">IMO No.</td><td>{imoNo || "—"}</td>
          </tr>
        </tbody>
      </table>

      <table className="insp-print-chk" style={{ marginTop: 12 }}>
        <thead><tr><th>Code</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Discount</th><th>Line Total</th></tr></thead>
        <tbody>
          {lineItems.map((item, i) => (
            <tr key={i}>
              <td style={{ fontFamily: "monospace" }}>{item.code}</td>
              <td>{item.description}</td>
              <td>{item.quantity}</td>
              <td>${item.unit_price.toFixed(2)}</td>
              <td>{item.discount_percent > 0 ? `${item.discount_percent}%` : "—"}</td>
              <td>${item.line_total.toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="finance-totals">
        <div className="finance-totals-row"><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></div>
        <div className="finance-totals-row"><span>Discount</span><span>-${discountTotal.toFixed(2)}</span></div>
        <div className="finance-totals-row grand"><span>Total</span><span>${total.toFixed(2)}</span></div>
      </div>

      <div style={{ marginTop: 24, borderTop: "1px solid #B9C0C6", paddingTop: 8, fontSize: 10, color: "var(--insp-muted)" }}>
        {issuedBy && <div>Issued by {issuedBy}{issuedAt ? ` — ${new Date(issuedAt).toLocaleString()}` : ""}</div>}
        <div style={{ marginTop: 4 }}>
          This {kind === "INVOICE" ? "invoice" : "quotation"} was generated by HMZC LTD's certification platform.
          Prices reflect HMZC's internal price list at the time of issue and are not subject to change once issued
          {kind === "INVOICE" ? "." : "; a formal invoice will confirm final pricing."}
        </div>
      </div>
    </div>
  );
}
