"""baseline: users, certificates, finance_items, quotations, invoices, audit_logs

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-21

Hand-written, not autogenerated — this sandbox has no live PostgreSQL
connection for `alembic revision --autogenerate` to inspect, so this was
built by reading every model in app/models/ directly instead. Table
order matters below: users first (everything else has a foreign key to
it), quotations before invoices (invoices.quotation_id references it).

Deliberately represents the schema as it stood *before*
users.must_change_password existed (see 0002_add_must_change_password.py)
even though that column is already in app/models/user.py as of this same
change — someone with an existing deployment already has every table
below (created via the previous Base.metadata.create_all() setup) and
is only missing that one new column. Splitting it into its own migration
means `alembic stamp 0001_baseline && alembic upgrade head` applies
*only* the genuinely new column to their real database, instead of a
baseline that (incorrectly) assumes it's also missing everything else.
See migrations/README.md for which command to actually run and when.

IMPORTANT — not run against a real database. Test this against a
disposable/staging Postgres instance before trusting it against
anything with real data.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None

# Was inferred from SQLAlchemy's default enum-naming behavior (flagged
# directly as unverified in a readiness review, since there was no live
# database to confirm it against). Fixed at the source instead:
# app/models/user.py now explicitly names this Column(Enum(UserRole,
# name="userrole"), ...) rather than leaving it implicit, so this line
# is a guaranteed match with the model, not a guess about what
# SQLAlchemy would have picked on its own.
user_role_enum = sa.Enum("admin", "inspector", "finance", "client", name="userrole")


def upgrade() -> None:
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("email", sa.String(), nullable=False, unique=True, index=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("role", user_role_enum, nullable=False, server_default="inspector"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    op.create_table(
        "finance_items",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("code", sa.String(), nullable=False, unique=True, index=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    op.create_table(
        "quotations",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("quotation_no", sa.String(), nullable=False, unique=True, index=True),
        sa.Column("customer", sa.String(), nullable=False),
        sa.Column("vessel_name", sa.String(), nullable=True),
        sa.Column("imo_no", sa.String(), nullable=True, index=True),
        sa.Column("status", sa.String(), nullable=False, server_default="draft"),
        sa.Column("line_items", sa.JSON(), nullable=False),
        sa.Column("subtotal", sa.Float(), nullable=False, server_default="0"),
        sa.Column("discount_total", sa.Float(), nullable=False, server_default="0"),
        sa.Column("total", sa.Float(), nullable=False, server_default="0"),
        sa.Column("issued_by_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("invoice_no", sa.String(), nullable=False, unique=True, index=True),
        sa.Column("quotation_id", sa.Integer(), sa.ForeignKey("quotations.id"), nullable=True),
        sa.Column("customer", sa.String(), nullable=False),
        sa.Column("vessel_name", sa.String(), nullable=True),
        sa.Column("imo_no", sa.String(), nullable=True, index=True),
        sa.Column("status", sa.String(), nullable=False, server_default="draft"),
        sa.Column("line_items", sa.JSON(), nullable=False),
        sa.Column("subtotal", sa.Float(), nullable=False, server_default="0"),
        sa.Column("discount_total", sa.Float(), nullable=False, server_default="0"),
        sa.Column("total", sa.Float(), nullable=False, server_default="0"),
        sa.Column("issued_by_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    op.create_table(
        "certificates",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("cert_no", sa.String(), nullable=False, unique=True, index=True),
        sa.Column("equipment_type", sa.String(), nullable=False),
        sa.Column("vessel_name", sa.String(), nullable=True),
        sa.Column("imo_no", sa.String(), nullable=True, index=True),
        sa.Column("status", sa.String(), nullable=False, server_default="draft"),
        sa.Column("date_of_servicing", sa.String(), nullable=True),
        sa.Column("issued_by_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=True),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("certificates")
    op.drop_table("invoices")
    op.drop_table("quotations")
    op.drop_table("finance_items")
    op.drop_table("users")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
